language: python
python:
- "3.6"
services: mongodb
jobs:  
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: bats test.bats
